import {StyleSheet} from 'react-native';
export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  profile_card: {
    width:'80%',
    height:'60%',
    backgroundColor:'red',
    borderRadius:25,
    alignItems : 'center',
    justifyContent:'center',
    backgroundColor:'lightblue',
    position:'relative'
  },
  profileImage:{
    width:100,
    height:100,
    borderRadius:50
  },
  tagArea:{
    display:'flex',
    flexDirection:'row',
    marginTop:20,
    flexWrap:'wrap',
    alignItems:'center',
    justifyContent:'center'
  },
  tags:{
    padding:8,
    backgroundColor:'blue',
    color:'white',
    marginRight:5,
    borderRadius:15,
    textAlign:'center',
    marginTop:10
  },
  footer:{
    display:'flex',
    flexDirection:'row',
    paddingVertical:15,
    alignItems:'center',
    bottom:0,
    justifyContent:'space-evenly',
    borderTopWidth:1,
    borderTopColor:'#9be78269',
    width:'100%',
    position:'absolute'
  },
  header:{
    position:'absolute',
    top:0,
    display:'flex',
    flexDirection:'row',
    justifyContent:'space-between',
    width:'100%',
    paddingHorizontal:30,
    paddingVertical:10,
    alignItems:'center'
  },
  story:{
    display:'flex',
    flexDirection:'column',
    justifyContent:'center',
    alignItems:'center',
  },
  storyImage:{
    width:70,
    height:70,
    borderRadius:35,
    borderColor:'red',
  },
  storySection:{
    display:'flex',
    flexDirection:'row',
    justifyContent:'space-around',
    height:100,
    position:'relative',
    width:'100%',
  },
  profileInfo:{
    display:'flex',
    flexDirection:'row',
    alignItems:'center',
    width:'100%',
    justifyContent:'flex-start',
    marginBottom:10
  },
  postArea:{
    padding:15
  },
  post_details:{
    marginTop:10,
    display:'flex',
    flexDirection:'row',
    alignItems:'center',
    paddingHorizontal:7,
    marginBottom:5
  }
});